# Spring Boot Application Configuration for Axonique Backend

# Server Configuration

server.port=8080
server.servlet.context-path=/

# Database Configuration - PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-restless-bar-amh454yb-pooler.c-5.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_AETr5GIbQCh3}

# JPA/Hibernate Configuration
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.generate_statistics=false

# Application Name
spring.application.name=Axonique Backend API

# Logging
logging.level.root=INFO
logging.level.com.axonique_backend=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Mail Configuration (Placeholder for local testing)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.mail.resend.api=${MAIL_RESEND_API:re_buRJ3DzW_53HTmbYVh3FaUKSeQGVhpCDp}
app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}


# Reduce DB connection pool size
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Disable open-in-view (saves memory)
spring.jpa.open-in-view=false