package com.axonique_backend.axonique_backend.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * BulkOrder — wholesale order placed by a retailer.
 *
 * Inheritance : extends BaseEntity (id + audit timestamps).
 * Composition : owns a list of BulkOrderItems.
 * Encapsulation: status transitions are guarded by BulkOrderService.
 *
 * SOLID S: holds bulk-order data only; discount / pricing logic lives
 *          in BulkOrderService, not here.
 */
@Entity
@Table(name = "bulk_orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BulkOrder extends BaseEntity {

    /**
     * Human-readable reference number — e.g. BLK-0042.
     * Generated by a DB trigger (trg_bulk_order_ref) on INSERT
     * when left blank; we pass an empty string from the service
     * so the trigger fires.
     */
    @Column(nullable = false, unique = true, length = 20)
    private String ref;

    /** FK to the retailer who placed this order. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "retailer_user_id", nullable = false)
    private User retailer;

    @NotBlank
    @Column(nullable = false)
    private String companyName;

    @NotBlank
    @Column(nullable = false)
    private String contactPerson;

    @NotBlank
    @Column(nullable = false)
    private String contactEmail;

    @NotBlank
    @Column(nullable = false, columnDefinition = "TEXT")
    private String deliveryAddress;

    @Column(columnDefinition = "TEXT")
    private String notes;

    /** Sum of (unitPrice × qty) before discount. */
    @NotNull
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal subtotal;

    /** Discount percentage applied (e.g. 10.00 for 10 %). */
    @NotNull
    @Column(nullable = false, precision = 5, scale = 2)
    @Builder.Default
    private BigDecimal discountPct = BigDecimal.ZERO;

    /** Monetary value of the discount. */
    @NotNull
    @Column(nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal discountAmount = BigDecimal.ZERO;

    /** subtotal − discountAmount. */
    @NotNull
    @Column(name = "grand_total", nullable = false, precision = 12, scale = 2)
    private BigDecimal grandTotal;

    /** Total number of units across all line items. */
    @Column(nullable = false)
    @Builder.Default
    private int totalQty = 0;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private BulkOrderStatus status = BulkOrderStatus.PENDING;

    /**
     * Composition: BulkOrder owns its line items.
     * CascadeType.ALL ensures items are persisted / deleted with the order.
     */
    @OneToMany(mappedBy = "bulkOrder", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<BulkOrderItem> items = new ArrayList<>();

    // ----- Relationship helpers -----

    public void addItem(BulkOrderItem item) {
        items.add(item);
        item.setBulkOrder(this);
    }
}
